name: Code check 
on:
  push:
    branches: [main]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: action/checkout@v4

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
